## Basic Download For ML Pipeline

In [5]:
!pip install wordcloud

import sys
!{sys.executable} -m pip install nltk

Requirement already satisfied: wordcloud in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.6)
Requirement already satisfied: numpy>=1.19.3 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from wordcloud) (2.4.4)
Requirement already satisfied: pillow in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from wordcloud) (12.2.0)
Requirement already satisfied: matplotlib in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from wordcloud) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->wordcloud) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages (from matplotlib->wordcloud) (26.2)
Requirement already satisfied: pyparsing>=3 in C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Collecting defusedxml (from nltk)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: click in c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.4.1)
Collecting joblib (from nltk)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.9.10-cp313-cp313-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (4.68.2)
Requirement already satisfied: colorama in C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages (from click->nltk) (0.4.6)
Collecting cloudpickle>=3.0 (from joblib->nltk)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 7.0 MB/s  0:00:00
Downloading regex-2026.9.10-cp313-cp313-win_amd64.whl (277 kB)
Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Installing collected packages: regex, defusedxml, cloudpickle, joblib, nltk

   ---------------------------------------- 0/5 [regex]
   -------- ------------------------------- 1/5 [defusedxml]
   ---------------- ----------------------- 2/5 [cloudpickle]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   ---------------------------------------- 5/5 [nltk]

Successfully installed cloudpickle-3.1.2 defusedxml-0.7.1 joblib-1.6.0 nltk-3.10.3 regex-2026.9.10

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
# Importing necessary libraries
import numpy as np        # For numerical operations
import pandas as pd       # For data manipulation and analysis
import matplotlib.pyplot as plt  # For data visualization
%matplotlib inline

# Importing WordCloud for text visualization
from wordcloud import WordCloud

# Importing NLTK for natural language processing
import nltk
from nltk.corpus import stopwords    # For stopwords


# Downloading NLTK data
nltk.download('stopwords')   # Downloading stopwords data
nltk.download('punkt')       # Downloading tokenizer data

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [7]:
df=pd.read_csv("spam.csv")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [8]:
df.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
# Rename the columns name
df.rename(columns = {'v1': 'target', 'v2': 'text'}, inplace = True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

## Data Preprocessing

In [11]:
import sys
!{sys.executable} -m pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.24.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.2 MB 3.0 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.2 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.2 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.2 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.2 MB 2.9 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.2 MB 1.1 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.2 MB 1.1 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.2 MB 1.1 MB/s eta 0:00:07
   -------- ------------------------------- 1.8/8.2 MB 920.9 kB/s eta 0:00:07
   -------- ------------------------------- 1.8/8.2 MB 920.9 kB/s eta 0:00:07
   -------- ------------------------------- 1.8/8.2 MB 920.9 kB/s eta 0:00:07
   ---------- ----------------------------- 2.1/8.2 MB 769.2 kB/s eta 0:00:08
   ---------- ----------------------------- 2.1/8.2 MB 769.2 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.2 MB 753.2 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.2 MB 753.2 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.2 MB 753.2 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.2 MB 753.2 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.2 MB 638.8 kB/s eta 0:00:09
   -------------- ------------------------- 2.9/8.2 MB 327.8 kB/s eta 0:00:17
   -------------- ------------------------- 2.9/8.2 MB 327.8 kB/s eta 0:00:17
   -------------- ------------------------- 2.9/8.2 MB 327.8 kB/s eta 0:00:17
   -------------- ------------------------- 2.9/8.2 MB 327.8 kB/s eta 0:00:17
   -------------- ------------------------- 2.9/8.2 MB 327.8 kB/s eta 0:00:17
   -------------- ------------------------- 2.9/8.2 MB 327.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.2 MB 307.6 kB/s eta 0:00:17
   ---------------- ----------------------- 3.4/8.2 MB 269.6 kB/s eta 0:00:18
   ----------------- ---------------------- 3.7/8.2 MB 284.4 kB/s eta 0:00:17
   ----------------- ---------------------- 3.7/8.2 MB 284.4 kB/s eta 0:00:17
   ------------------- -------------------- 3.9/8.2 MB 298.9 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.2 MB 313.1 kB/s eta 0:00:13
   --------------------- ------------------ 4.5/8.2 MB 327.4 kB/s eta 0:00:12
   ---------------------- ----------------- 4.7/8.2 MB 341.2 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.2 MB 355.0 kB/s eta 0:00:10
   ------------------------- -------------- 5.2/8.2 MB 368.6 kB/s eta 0:00:09
   -------------------------- ------------- 5.5/8.2 MB 381.2 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.2 MB 381.2 kB/s eta 0:00:08
   ---------------------------- ----------- 5.8/8.2 MB 393.2 kB/s eta 0:00:07
   ------------------------------ --------- 6.3/8.2 MB 419.1 kB/s eta 0:00:05
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.2 MB 431.7 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.2 MB 397.9 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.2 MB 311.3 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 277.3 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 277.3 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 277.3 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.2 MB 277.3 kB/s eta 0:00:04
   ------------------------------------ --- 7.6/8.2 MB 278.4 kB/s eta 0:00:03
   ------------------------------------ --- 7.6/8.2 MB 278.4 kB/s eta 0:00:03
   -------------------------------------- - 7.9/8.2 MB 283.4 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.2 MB 283.4 kB/s eta 0:00:02
   ---------------------------------------  8.1/8.2 MB 289.4 kB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 291.7 kB/s  0:00:27
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scikit-learn

   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   -------------------- ------------------- 1/2 [scikit-learn]
   ---------------------------------------- 2/2 [scikit-learn]

Successfully installed scikit-learn-1.9.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [13]:
len(df)

5572

In [14]:
#remove Duplicate
df = df.drop_duplicates(keep = 'first')
len(df)

5169

## Feature Engineering

In [16]:
# Importing the Porter Stemmer for text stemming
from nltk.stem.porter import PorterStemmer

# Importing the string module for handling special characters
import string

ps = PorterStemmer()

In [20]:
# Lowercase transformation and text preprocessing function
def transform_text(text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenization using NLTK
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
        
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    
    # Join the processed tokens back into a single string
    return " ".join(y)

In [21]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [22]:
transform_text("Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...")

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [23]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

,target,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [24]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfid = TfidfVectorizer(max_features = 500)

In [25]:
X = tfid.fit_transform(df['transformed_text']).toarray()
y = df['target'].values